-- dependencies = { "nvim-tree/nvim-web-devicons", "folke/todo-comments.nvim" },
-- local kms = vim.keymap.set

-- kms("n", "<leader>xx", "<cmd>TroubleToggle<CR>", { desc = "Open/close trouble list" })
-- DIAGS ACROSS PROJECT
-- kms("n", "<leader>xw", "<cmd>TroubleToggle workspace_diagnostics<CR>", { desc = "Open trouble workspace diagnostics" })
-- DIAGS CURRENT BUFFER
-- kms("n", "<leader>xb", "<cmd>TroubleToggle document_diagnostics<CR>", { desc = "Open diagnostics [B]uffer" })
-- kms("n", "<leader>xq", "<cmd>TroubleToggle quickfix<CR>", { desc = "Open trouble quickfix list" })
-- kms("n", "<leader>xl", "<cmd>TroubleToggle loclist<CR>", { desc = "Open trouble location list" })
-- kms("n", "<leader>xt", "<cmd>TodoTrouble<CR>", { desc = "Open todos in trouble" })
